catalog:
  '@pinia/colada': ^0.21.4
  pinia: ^3.0.4
  typescript: ~5.9.3
  valibot: ^1.2.0
  vue: ^3.5.26
  vue-router: ^4.6.4
  vuetify: ^3.11.8

catalogs:
  infra:
    '@hey-api/openapi-ts': ^0.92.4
    jiti: ^2.6.1
    simple-git-hooks: ^2.13.1
  lint:
    '@promise2/eslint-config': ^0.2.0
    '@typescript-eslint/eslint-plugin': ^8.54.0
    '@typescript-eslint/parser': ^8.54.0
    eslint: ^9.39.2
    eslint-config-prettier: ^10.1.8
    eslint-plugin-format: ^1.3.1
    eslint-plugin-prettier: ^5.5.5
    eslint-plugin-vue: ~10.7.0
    prettier: 3.8.1
    vue-eslint-parser: ^10.2.0
  type:
    '@types/node': ^24.10.9
  vite:
    '@vitejs/plugin-vue': ^6.0.3
    vite: ^7.3.1
    vite-plugin-vue-devtools: ^8.0.5
    vite-plugin-vuetify: ^2.1.3
  vue:
    '@tsconfig/node24': ^24.0.4
    '@vue/tsconfig': ^0.8.1
    npm-run-all2: ^8.0.4
    vue-tsc: ^3.2.2

cleanupUnusedCatalogs: true

overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  minimatch@<10.2.1: '>=10.2.1'
