// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions, type UseMutationOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import { deleteApiAdminAnnouncement, deleteApiReservationByReservationId, getApiAdminAccount, getApiAdminAccountInfo, getApiAdminAnnouncement, getApiAdminReservationInfo, getApiAdminRoom, getApiAdminRoomReservations, getApiGetLoginSessionSalt, getApiUserAnnoucements, getApiUserReservations, getApiVenueBuildings, getApiVenueByVenueIdInfo, getApiVenueCampuses, getApiVenueQuery, type Options, patchApiUserEditProfile, postApiAdminAnnoucement, postApiAdminReservationApproval, postApiLogin, postApiRegister, postApiUserChangePassword, postApiVenueByVenueIdReserve, putApiAdminAnnouncement, putApiAdminRoomUpdate } from '../sdk.gen';
import type { DeleteApiAdminAnnouncementData, DeleteApiAdminAnnouncementResponse, DeleteApiReservationByReservationIdData, DeleteApiReservationByReservationIdResponse, GetApiAdminAccountData, GetApiAdminAccountInfoData, GetApiAdminAnnouncementData, GetApiAdminReservationInfoData, GetApiAdminRoomData, GetApiAdminRoomReservationsData, GetApiGetLoginSessionSaltData, GetApiUserAnnoucementsData, GetApiUserReservationsData, GetApiVenueBuildingsData, GetApiVenueByVenueIdInfoData, GetApiVenueCampusesData, GetApiVenueQueryData, PatchApiUserEditProfileData, PatchApiUserEditProfileResponse, PostApiAdminAnnoucementData, PostApiAdminAnnoucementResponse, PostApiAdminReservationApprovalData, PostApiAdminReservationApprovalResponse, PostApiLoginData, PostApiLoginResponse, PostApiRegisterData, PostApiRegisterResponse, PostApiUserChangePasswordData, PostApiUserChangePasswordResponse, PostApiVenueByVenueIdReserveData, PostApiVenueByVenueIdReserveResponse, PutApiAdminAnnouncementData, PutApiAdminAnnouncementResponse, PutApiAdminRoomUpdateData, PutApiAdminRoomUpdateResponse } from '../types.gen';

/**
 * 登录
 */
export const postApiLoginMutation = (options?: Partial<Options<PostApiLoginData>>): UseMutationOptions<PostApiLoginResponse, Options<PostApiLoginData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postApiLogin({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * 修改密码
 *
 * 修改密码可选验证方式，要求登录验证与表单验证双通过。
 */
export const postApiUserChangePasswordMutation = (options?: Partial<Options<PostApiUserChangePasswordData>>): UseMutationOptions<PostApiUserChangePasswordResponse, Options<PostApiUserChangePasswordData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postApiUserChangePassword({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * 完善信息
 */
export const patchApiUserEditProfileMutation = (options?: Partial<Options<PatchApiUserEditProfileData>>): UseMutationOptions<PatchApiUserEditProfileResponse, Options<PatchApiUserEditProfileData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await patchApiUserEditProfile({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * 用户注册
 */
export const postApiRegisterMutation = (options?: Partial<Options<PostApiRegisterData>>): UseMutationOptions<PostApiRegisterResponse, Options<PostApiRegisterData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postApiRegister({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'path'> & {
        _id: string;
        baseUrl?: _JSONValue;
        body?: _JSONValue;
        query?: _JSONValue;
        tags?: _JSONValue;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (tags) {
        params.tags = tags as unknown as _JSONValue;
    }
    if (options?.body !== undefined) {
        const normalizedBody = serializeQueryKeyValue(options.body);
        if (normalizedBody !== undefined) {
            params.body = normalizedBody;
        }
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query !== undefined) {
        const normalizedQuery = serializeQueryKeyValue(options.query);
        if (normalizedQuery !== undefined) {
            params.query = normalizedQuery;
        }
    }
    return [params];
};

export const getApiGetLoginSessionSaltQueryKey = (options?: Options<GetApiGetLoginSessionSaltData>) => createQueryKey('getApiGetLoginSessionSalt', options);

/**
 * 获取密码盐值
 */
export const getApiGetLoginSessionSaltQuery = defineQueryOptions((options?: Options<GetApiGetLoginSessionSaltData>) => ({
    key: getApiGetLoginSessionSaltQueryKey(options),
    query: async (context) => {
        const { data } = await getApiGetLoginSessionSalt({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getApiVenueQueryQueryKey = (options?: Options<GetApiVenueQueryData>) => createQueryKey('getApiVenueQuery', options);

/**
 * 筛选场地
 *
 * 若没有筛选条件，全都默认为0
 *
 * 场地类别每个场地有且仅有一个，在前端显示为互斥选项；
 * 场地标签每个场地可以具有多个，可拓展；
 * timemap 待讨论；
 */
export const getApiVenueQueryQuery = defineQueryOptions((options?: Options<GetApiVenueQueryData>) => ({
    key: getApiVenueQueryQueryKey(options),
    query: async (context) => {
        const { data } = await getApiVenueQuery({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getApiVenueByVenueIdInfoQueryKey = (options: Options<GetApiVenueByVenueIdInfoData>) => createQueryKey('getApiVenueByVenueIdInfo', options);

/**
 * 场地详情
 */
export const getApiVenueByVenueIdInfoQuery = defineQueryOptions((options: Options<GetApiVenueByVenueIdInfoData>) => ({
    key: getApiVenueByVenueIdInfoQueryKey(options),
    query: async (context) => {
        const { data } = await getApiVenueByVenueIdInfo({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * 预约场地
 *
 * 预约表单需要根据场地详情中的“booking_availability”决定
 * - 如果为“open”，则大部分审批字段可选，下述为此情况下的表单
 * - 如果为“approval”，则大部分审批字段必选
 */
export const postApiVenueByVenueIdReserveMutation = (options?: Partial<Options<PostApiVenueByVenueIdReserveData>>): UseMutationOptions<PostApiVenueByVenueIdReserveResponse, Options<PostApiVenueByVenueIdReserveData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postApiVenueByVenueIdReserve({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * 取消预约
 */
export const deleteApiReservationByReservationIdMutation = (options?: Partial<Options<DeleteApiReservationByReservationIdData>>): UseMutationOptions<DeleteApiReservationByReservationIdResponse, Options<DeleteApiReservationByReservationIdData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await deleteApiReservationByReservationId({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getApiUserReservationsQueryKey = (options?: Options<GetApiUserReservationsData>) => createQueryKey('getApiUserReservations', options);

/**
 * 查询个人预约
 */
export const getApiUserReservationsQuery = defineQueryOptions((options?: Options<GetApiUserReservationsData>) => ({
    key: getApiUserReservationsQueryKey(options),
    query: async (context) => {
        const { data } = await getApiUserReservations({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getApiUserAnnoucementsQueryKey = (options?: Options<GetApiUserAnnoucementsData>) => createQueryKey('getApiUserAnnoucements', options);

/**
 * 查询公告/消息
 */
export const getApiUserAnnoucementsQuery = defineQueryOptions((options?: Options<GetApiUserAnnoucementsData>) => ({
    key: getApiUserAnnoucementsQueryKey(options),
    query: async (context) => {
        const { data } = await getApiUserAnnoucements({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getApiVenueBuildingsQueryKey = (options?: Options<GetApiVenueBuildingsData>) => createQueryKey('getApiVenueBuildings', options);

/**
 * 楼列表
 *
 * 获取用户有权读取的楼列表
 */
export const getApiVenueBuildingsQuery = defineQueryOptions((options?: Options<GetApiVenueBuildingsData>) => ({
    key: getApiVenueBuildingsQueryKey(options),
    query: async (context) => {
        const { data } = await getApiVenueBuildings({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getApiVenueCampusesQueryKey = (options?: Options<GetApiVenueCampusesData>) => createQueryKey('getApiVenueCampuses', options);

/**
 * 校区列表
 *
 * 获取用户有权读取的校区列表
 */
export const getApiVenueCampusesQuery = defineQueryOptions((options?: Options<GetApiVenueCampusesData>) => ({
    key: getApiVenueCampusesQueryKey(options),
    query: async (context) => {
        const { data } = await getApiVenueCampuses({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getApiAdminRoomQueryKey = (options?: Options<GetApiAdminRoomData>) => createQueryKey('getApiAdminRoom', options);

/**
 * 总览所管场地
 */
export const getApiAdminRoomQuery = defineQueryOptions((options?: Options<GetApiAdminRoomData>) => ({
    key: getApiAdminRoomQueryKey(options),
    query: async (context) => {
        const { data } = await getApiAdminRoom({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getApiAdminRoomReservationsQueryKey = (options?: Options<GetApiAdminRoomReservationsData>) => createQueryKey('getApiAdminRoomReservations', options);

/**
 * 总览单个场地所有预约
 */
export const getApiAdminRoomReservationsQuery = defineQueryOptions((options?: Options<GetApiAdminRoomReservationsData>) => ({
    key: getApiAdminRoomReservationsQueryKey(options),
    query: async (context) => {
        const { data } = await getApiAdminRoomReservations({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getApiAdminReservationInfoQueryKey = (options?: Options<GetApiAdminReservationInfoData>) => createQueryKey('getApiAdminReservationInfo', options);

/**
 * 查看预约详情
 */
export const getApiAdminReservationInfoQuery = defineQueryOptions((options?: Options<GetApiAdminReservationInfoData>) => ({
    key: getApiAdminReservationInfoQueryKey(options),
    query: async (context) => {
        const { data } = await getApiAdminReservationInfo({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * 审批预约
 */
export const postApiAdminReservationApprovalMutation = (options?: Partial<Options<PostApiAdminReservationApprovalData>>): UseMutationOptions<PostApiAdminReservationApprovalResponse, Options<PostApiAdminReservationApprovalData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postApiAdminReservationApproval({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * 更新场地信息
 */
export const putApiAdminRoomUpdateMutation = (options?: Partial<Options<PutApiAdminRoomUpdateData>>): UseMutationOptions<PutApiAdminRoomUpdateResponse, Options<PutApiAdminRoomUpdateData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await putApiAdminRoomUpdate({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getApiAdminAccountQueryKey = (options?: Options<GetApiAdminAccountData>) => createQueryKey('getApiAdminAccount', options);

/**
 * 总览所有被管理的账户
 */
export const getApiAdminAccountQuery = defineQueryOptions((options?: Options<GetApiAdminAccountData>) => ({
    key: getApiAdminAccountQueryKey(options),
    query: async (context) => {
        const { data } = await getApiAdminAccount({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getApiAdminAccountInfoQueryKey = (options?: Options<GetApiAdminAccountInfoData>) => createQueryKey('getApiAdminAccountInfo', options);

/**
 * 查看用户信息
 */
export const getApiAdminAccountInfoQuery = defineQueryOptions((options?: Options<GetApiAdminAccountInfoData>) => ({
    key: getApiAdminAccountInfoQueryKey(options),
    query: async (context) => {
        const { data } = await getApiAdminAccountInfo({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * 发布公告
 */
export const postApiAdminAnnoucementMutation = (options?: Partial<Options<PostApiAdminAnnoucementData>>): UseMutationOptions<PostApiAdminAnnoucementResponse, Options<PostApiAdminAnnoucementData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postApiAdminAnnoucement({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * 删除公告
 */
export const deleteApiAdminAnnouncementMutation = (options?: Partial<Options<DeleteApiAdminAnnouncementData>>): UseMutationOptions<DeleteApiAdminAnnouncementResponse, Options<DeleteApiAdminAnnouncementData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await deleteApiAdminAnnouncement({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getApiAdminAnnouncementQueryKey = (options?: Options<GetApiAdminAnnouncementData>) => createQueryKey('getApiAdminAnnouncement', options);

/**
 * 查看发布的公告
 */
export const getApiAdminAnnouncementQuery = defineQueryOptions((options?: Options<GetApiAdminAnnouncementData>) => ({
    key: getApiAdminAnnouncementQueryKey(options),
    query: async (context) => {
        const { data } = await getApiAdminAnnouncement({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * 更新公告
 */
export const putApiAdminAnnouncementMutation = (options?: Partial<Options<PutApiAdminAnnouncementData>>): UseMutationOptions<PutApiAdminAnnouncementResponse, Options<PutApiAdminAnnouncementData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await putApiAdminAnnouncement({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});
