// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions, type UseMutationOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import { deleteApiApplicationByApplicationId, deleteApiNotificationByNotificationId, deleteApiVenueByVenueId, getApiAccount, getApiFileByFiletoken, getApiLoginSessionSalt, getApiNotification, getApiNotificationRead, getApiSystemPermission, getApiUserApplication, getApiUserNotification, getApiUserProfile, getApiUserProfileByUid, getApiVenue, getApiVenueByVenueIdApplication, getApiVenueLocations, type Options, postApiFile, postApiLogin, postApiNotification, postApiRegister, postApiUserChangePassword, postApiVenueByVenueIdApplication, putApiApplicationByApplicationId, putApiNotificationByNotificationId, putApiUserProfile, putApiUserSystemPermission, putApiVenue, putApiVenueByVenueId } from '../sdk.gen';
import type { DeleteApiApplicationByApplicationIdData, DeleteApiApplicationByApplicationIdResponse, DeleteApiNotificationByNotificationIdData, DeleteApiNotificationByNotificationIdResponse, DeleteApiVenueByVenueIdData, DeleteApiVenueByVenueIdResponse, GetApiAccountData, GetApiFileByFiletokenData, GetApiLoginSessionSaltData, GetApiNotificationData, GetApiNotificationReadData, GetApiSystemPermissionData, GetApiUserApplicationData, GetApiUserNotificationData, GetApiUserProfileByUidData, GetApiUserProfileData, GetApiVenueByVenueIdApplicationData, GetApiVenueData, GetApiVenueLocationsData, PostApiFileData, PostApiFileResponse, PostApiLoginData, PostApiLoginResponse, PostApiNotificationData, PostApiNotificationResponse, PostApiRegisterData, PostApiRegisterResponse, PostApiUserChangePasswordData, PostApiUserChangePasswordResponse, PostApiVenueByVenueIdApplicationData, PostApiVenueByVenueIdApplicationResponse, PutApiApplicationByApplicationIdData, PutApiApplicationByApplicationIdResponse, PutApiNotificationByNotificationIdData, PutApiNotificationByNotificationIdResponse, PutApiUserProfileData, PutApiUserProfileResponse, PutApiUserSystemPermissionData, PutApiUserSystemPermissionResponse, PutApiVenueByVenueIdData, PutApiVenueByVenueIdResponse, PutApiVenueData, PutApiVenueResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'path'> & {
        _id: string;
        baseUrl?: _JSONValue;
        body?: _JSONValue;
        query?: _JSONValue;
        tags?: _JSONValue;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (tags) {
        params.tags = tags as unknown as _JSONValue;
    }
    if (options?.body !== undefined) {
        const normalizedBody = serializeQueryKeyValue(options.body);
        if (normalizedBody !== undefined) {
            params.body = normalizedBody;
        }
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query !== undefined) {
        const normalizedQuery = serializeQueryKeyValue(options.query);
        if (normalizedQuery !== undefined) {
            params.query = normalizedQuery;
        }
    }
    return [params];
};

export const getApiSystemPermissionQueryKey = (options?: Options<GetApiSystemPermissionData>) => createQueryKey('getApiSystemPermission', options);

/**
 * 获取系统权限列表
 */
export const getApiSystemPermissionQuery = defineQueryOptions((options?: Options<GetApiSystemPermissionData>) => ({
    key: getApiSystemPermissionQueryKey(options),
    query: async (context) => {
        const { data } = await getApiSystemPermission({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * 修改用户权限
 */
export const putApiUserSystemPermissionMutation = (options?: Partial<Options<PutApiUserSystemPermissionData>>): UseMutationOptions<PutApiUserSystemPermissionResponse, Options<PutApiUserSystemPermissionData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await putApiUserSystemPermission({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getApiUserProfileQueryKey = (options?: Options<GetApiUserProfileData>) => createQueryKey('getApiUserProfile', options);

/**
 * 获取自身信息
 */
export const getApiUserProfileQuery = defineQueryOptions((options?: Options<GetApiUserProfileData>) => ({
    key: getApiUserProfileQueryKey(options),
    query: async (context) => {
        const { data } = await getApiUserProfile({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * 完善信息
 */
export const putApiUserProfileMutation = (options?: Partial<Options<PutApiUserProfileData>>): UseMutationOptions<PutApiUserProfileResponse, Options<PutApiUserProfileData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await putApiUserProfile({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getApiUserProfileByUidQueryKey = (options: Options<GetApiUserProfileByUidData>) => createQueryKey('getApiUserProfileByUid', options);

/**
 * 获取任意用户信息
 *
 * 该接口需要 UserManagement 系统权限
 */
export const getApiUserProfileByUidQuery = defineQueryOptions((options: Options<GetApiUserProfileByUidData>) => ({
    key: getApiUserProfileByUidQueryKey(options),
    query: async (context) => {
        const { data } = await getApiUserProfileByUid({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * 登录
 */
export const postApiLoginMutation = (options?: Partial<Options<PostApiLoginData>>): UseMutationOptions<PostApiLoginResponse, Options<PostApiLoginData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postApiLogin({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * 修改密码
 *
 * 修改密码可选验证方式，要求登录验证与表单验证双通过。
 */
export const postApiUserChangePasswordMutation = (options?: Partial<Options<PostApiUserChangePasswordData>>): UseMutationOptions<PostApiUserChangePasswordResponse, Options<PostApiUserChangePasswordData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postApiUserChangePassword({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * 用户注册
 */
export const postApiRegisterMutation = (options?: Partial<Options<PostApiRegisterData>>): UseMutationOptions<PostApiRegisterResponse, Options<PostApiRegisterData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postApiRegister({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getApiLoginSessionSaltQueryKey = (options?: Options<GetApiLoginSessionSaltData>) => createQueryKey('getApiLoginSessionSalt', options);

/**
 * 获取密码盐值
 */
export const getApiLoginSessionSaltQuery = defineQueryOptions((options?: Options<GetApiLoginSessionSaltData>) => ({
    key: getApiLoginSessionSaltQueryKey(options),
    query: async (context) => {
        const { data } = await getApiLoginSessionSalt({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getApiVenueQueryKey = (options: Options<GetApiVenueData>) => createQueryKey('getApiVenue', options);

/**
 * 筛选场地
 *
 * 若没有筛选条件，全都默认为0
 *
 * 场地类别每个场地有且仅有一个，在前端显示为互斥选项；
 * 场地标签每个场地可以具有多个，可拓展；
 * timemap 待讨论；
 */
export const getApiVenueQuery = defineQueryOptions((options: Options<GetApiVenueData>) => ({
    key: getApiVenueQueryKey(options),
    query: async (context) => {
        const { data } = await getApiVenue({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * 创建场地
 */
export const putApiVenueMutation = (options?: Partial<Options<PutApiVenueData>>): UseMutationOptions<PutApiVenueResponse, Options<PutApiVenueData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await putApiVenue({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * 删除场地
 */
export const deleteApiVenueByVenueIdMutation = (options?: Partial<Options<DeleteApiVenueByVenueIdData>>): UseMutationOptions<DeleteApiVenueByVenueIdResponse, Options<DeleteApiVenueByVenueIdData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await deleteApiVenueByVenueId({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * 更新场地信息
 */
export const putApiVenueByVenueIdMutation = (options?: Partial<Options<PutApiVenueByVenueIdData>>): UseMutationOptions<PutApiVenueByVenueIdResponse, Options<PutApiVenueByVenueIdData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await putApiVenueByVenueId({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getApiVenueLocationsQueryKey = (options?: Options<GetApiVenueLocationsData>) => createQueryKey('getApiVenueLocations', options);

/**
 * 获取楼校区表
 */
export const getApiVenueLocationsQuery = defineQueryOptions((options?: Options<GetApiVenueLocationsData>) => ({
    key: getApiVenueLocationsQueryKey(options),
    query: async (context) => {
        const { data } = await getApiVenueLocations({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getApiVenueByVenueIdApplicationQueryKey = (options: Options<GetApiVenueByVenueIdApplicationData>) => createQueryKey('getApiVenueByVenueIdApplication', options);

/**
 * 总览单个场地所有预约
 */
export const getApiVenueByVenueIdApplicationQuery = defineQueryOptions((options: Options<GetApiVenueByVenueIdApplicationData>) => ({
    key: getApiVenueByVenueIdApplicationQueryKey(options),
    query: async (context) => {
        const { data } = await getApiVenueByVenueIdApplication({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * 预约场地
 */
export const postApiVenueByVenueIdApplicationMutation = (options?: Partial<Options<PostApiVenueByVenueIdApplicationData>>): UseMutationOptions<PostApiVenueByVenueIdApplicationResponse, Options<PostApiVenueByVenueIdApplicationData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postApiVenueByVenueIdApplication({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * 取消预约
 */
export const deleteApiApplicationByApplicationIdMutation = (options?: Partial<Options<DeleteApiApplicationByApplicationIdData>>): UseMutationOptions<DeleteApiApplicationByApplicationIdResponse, Options<DeleteApiApplicationByApplicationIdData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await deleteApiApplicationByApplicationId({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * 审批预约
 */
export const putApiApplicationByApplicationIdMutation = (options?: Partial<Options<PutApiApplicationByApplicationIdData>>): UseMutationOptions<PutApiApplicationByApplicationIdResponse, Options<PutApiApplicationByApplicationIdData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await putApiApplicationByApplicationId({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getApiUserApplicationQueryKey = (options: Options<GetApiUserApplicationData>) => createQueryKey('getApiUserApplication', options);

/**
 * 查询个人预约
 */
export const getApiUserApplicationQuery = defineQueryOptions((options: Options<GetApiUserApplicationData>) => ({
    key: getApiUserApplicationQueryKey(options),
    query: async (context) => {
        const { data } = await getApiUserApplication({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * 上传文件
 */
export const postApiFileMutation = (options?: Partial<Options<PostApiFileData>>): UseMutationOptions<PostApiFileResponse, Options<PostApiFileData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postApiFile({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getApiFileByFiletokenQueryKey = (options: Options<GetApiFileByFiletokenData>) => createQueryKey('getApiFileByFiletoken', options);

/**
 * 下载文件
 */
export const getApiFileByFiletokenQuery = defineQueryOptions((options: Options<GetApiFileByFiletokenData>) => ({
    key: getApiFileByFiletokenQueryKey(options),
    query: async (context) => {
        const { data } = await getApiFileByFiletoken({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getApiAccountQueryKey = (options: Options<GetApiAccountData>) => createQueryKey('getApiAccount', options);

/**
 * 总览所有被管理的账户
 */
export const getApiAccountQuery = defineQueryOptions((options: Options<GetApiAccountData>) => ({
    key: getApiAccountQueryKey(options),
    query: async (context) => {
        const { data } = await getApiAccount({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getApiNotificationQueryKey = (options?: Options<GetApiNotificationData>) => createQueryKey('getApiNotification', options);

/**
 * 查看公告
 */
export const getApiNotificationQuery = defineQueryOptions((options?: Options<GetApiNotificationData>) => ({
    key: getApiNotificationQueryKey(options),
    query: async (context) => {
        const { data } = await getApiNotification({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * 发布公告
 */
export const postApiNotificationMutation = (options?: Partial<Options<PostApiNotificationData>>): UseMutationOptions<PostApiNotificationResponse, Options<PostApiNotificationData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postApiNotification({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * 删除公告
 */
export const deleteApiNotificationByNotificationIdMutation = (options?: Partial<Options<DeleteApiNotificationByNotificationIdData>>): UseMutationOptions<DeleteApiNotificationByNotificationIdResponse, Options<DeleteApiNotificationByNotificationIdData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await deleteApiNotificationByNotificationId({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * 更新公告
 */
export const putApiNotificationByNotificationIdMutation = (options?: Partial<Options<PutApiNotificationByNotificationIdData>>): UseMutationOptions<PutApiNotificationByNotificationIdResponse, Options<PutApiNotificationByNotificationIdData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await putApiNotificationByNotificationId({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getApiUserNotificationQueryKey = (options?: Options<GetApiUserNotificationData>) => createQueryKey('getApiUserNotification', options);

/**
 * 获取个人发布的公告
 */
export const getApiUserNotificationQuery = defineQueryOptions((options?: Options<GetApiUserNotificationData>) => ({
    key: getApiUserNotificationQueryKey(options),
    query: async (context) => {
        const { data } = await getApiUserNotification({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getApiNotificationReadQueryKey = (options?: Options<GetApiNotificationReadData>) => createQueryKey('getApiNotificationRead', options);

/**
 * 获取用户是否有未读通告
 */
export const getApiNotificationReadQuery = defineQueryOptions((options?: Options<GetApiNotificationReadData>) => ({
    key: getApiNotificationReadQueryKey(options),
    query: async (context) => {
        const { data } = await getApiNotificationRead({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));
