// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { DeleteApiApplicationByApplicationIdData, DeleteApiApplicationByApplicationIdResponses, DeleteApiNotificationByNotificationIdData, DeleteApiNotificationByNotificationIdResponses, DeleteApiVenueByVenueIdData, DeleteApiVenueByVenueIdResponses, GetApiAccountData, GetApiAccountResponses, GetApiFileByFiletokenData, GetApiFileByFiletokenResponses, GetApiLoginSessionSaltData, GetApiLoginSessionSaltResponses, GetApiNotificationData, GetApiNotificationReadData, GetApiNotificationReadResponses, GetApiNotificationResponses, GetApiSystemPermissionData, GetApiSystemPermissionResponses, GetApiUserApplicationData, GetApiUserApplicationResponses, GetApiUserNotificationData, GetApiUserNotificationResponses, GetApiUserProfileByUidData, GetApiUserProfileByUidResponses, GetApiUserProfileData, GetApiUserProfileResponses, GetApiVenueByVenueIdApplicationData, GetApiVenueByVenueIdApplicationResponses, GetApiVenueData, GetApiVenueLocationsData, GetApiVenueLocationsResponses, GetApiVenueResponses, PostApiFileData, PostApiFileResponses, PostApiLoginData, PostApiLoginResponses, PostApiNotificationData, PostApiNotificationResponses, PostApiRegisterData, PostApiRegisterResponses, PostApiUserChangePasswordData, PostApiUserChangePasswordResponses, PostApiVenueByVenueIdApplicationData, PostApiVenueByVenueIdApplicationResponses, PutApiApplicationByApplicationIdData, PutApiApplicationByApplicationIdResponses, PutApiNotificationByNotificationIdData, PutApiNotificationByNotificationIdResponses, PutApiUserProfileData, PutApiUserProfileResponses, PutApiUserSystemPermissionData, PutApiUserSystemPermissionResponses, PutApiVenueByVenueIdData, PutApiVenueByVenueIdResponses, PutApiVenueData, PutApiVenueResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 获取系统权限列表
 */
export const getApiSystemPermission = <ThrowOnError extends boolean = false>(options?: Options<GetApiSystemPermissionData, ThrowOnError>) => (options?.client ?? client).get<GetApiSystemPermissionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/system-permission',
    ...options
});

/**
 * 修改用户权限
 */
export const putApiUserSystemPermission = <ThrowOnError extends boolean = false>(options: Options<PutApiUserSystemPermissionData, ThrowOnError>) => (options.client ?? client).put<PutApiUserSystemPermissionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/system-permission',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 获取自身信息
 */
export const getApiUserProfile = <ThrowOnError extends boolean = false>(options?: Options<GetApiUserProfileData, ThrowOnError>) => (options?.client ?? client).get<GetApiUserProfileResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/profile',
    ...options
});

/**
 * 完善信息
 */
export const putApiUserProfile = <ThrowOnError extends boolean = false>(options: Options<PutApiUserProfileData, ThrowOnError>) => (options.client ?? client).put<PutApiUserProfileResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/profile',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 获取任意用户信息
 *
 * 该接口需要 UserManagement 系统权限
 */
export const getApiUserProfileByUid = <ThrowOnError extends boolean = false>(options: Options<GetApiUserProfileByUidData, ThrowOnError>) => (options.client ?? client).get<GetApiUserProfileByUidResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/profile/{uid}',
    ...options
});

/**
 * 登录
 */
export const postApiLogin = <ThrowOnError extends boolean = false>(options: Options<PostApiLoginData, ThrowOnError>) => (options.client ?? client).post<PostApiLoginResponses, unknown, ThrowOnError>({
    url: '/api/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 修改密码
 *
 * 修改密码可选验证方式，要求登录验证与表单验证双通过。
 */
export const postApiUserChangePassword = <ThrowOnError extends boolean = false>(options: Options<PostApiUserChangePasswordData, ThrowOnError>) => (options.client ?? client).post<PostApiUserChangePasswordResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/change-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 用户注册
 */
export const postApiRegister = <ThrowOnError extends boolean = false>(options: Options<PostApiRegisterData, ThrowOnError>) => (options.client ?? client).post<PostApiRegisterResponses, unknown, ThrowOnError>({
    url: '/api/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 获取密码盐值
 */
export const getApiLoginSessionSalt = <ThrowOnError extends boolean = false>(options?: Options<GetApiLoginSessionSaltData, ThrowOnError>) => (options?.client ?? client).get<GetApiLoginSessionSaltResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/login-session-salt',
    ...options
});

/**
 * 筛选场地
 *
 * 若没有筛选条件，全都默认为0
 *
 * 场地类别每个场地有且仅有一个，在前端显示为互斥选项；
 * 场地标签每个场地可以具有多个，可拓展；
 * timemap 待讨论；
 */
export const getApiVenue = <ThrowOnError extends boolean = false>(options: Options<GetApiVenueData, ThrowOnError>) => (options.client ?? client).get<GetApiVenueResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/venue',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * 创建场地
 */
export const putApiVenue = <ThrowOnError extends boolean = false>(options: Options<PutApiVenueData, ThrowOnError>) => (options.client ?? client).put<PutApiVenueResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/venue',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除场地
 */
export const deleteApiVenueByVenueId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiVenueByVenueIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiVenueByVenueIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/venue/{venue_id}',
    ...options
});

/**
 * 更新场地信息
 */
export const putApiVenueByVenueId = <ThrowOnError extends boolean = false>(options: Options<PutApiVenueByVenueIdData, ThrowOnError>) => (options.client ?? client).put<PutApiVenueByVenueIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/venue/{venue_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 获取楼校区表
 */
export const getApiVenueLocations = <ThrowOnError extends boolean = false>(options?: Options<GetApiVenueLocationsData, ThrowOnError>) => (options?.client ?? client).get<GetApiVenueLocationsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/venue/locations',
    ...options
});

/**
 * 总览单个场地所有预约
 */
export const getApiVenueByVenueIdApplication = <ThrowOnError extends boolean = false>(options: Options<GetApiVenueByVenueIdApplicationData, ThrowOnError>) => (options.client ?? client).get<GetApiVenueByVenueIdApplicationResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/venue/{venue_id}/application',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * 预约场地
 */
export const postApiVenueByVenueIdApplication = <ThrowOnError extends boolean = false>(options: Options<PostApiVenueByVenueIdApplicationData, ThrowOnError>) => (options.client ?? client).post<PostApiVenueByVenueIdApplicationResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/venue/{venue_id}/application',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 取消预约
 */
export const deleteApiApplicationByApplicationId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiApplicationByApplicationIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiApplicationByApplicationIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/application/{application_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 审批预约
 */
export const putApiApplicationByApplicationId = <ThrowOnError extends boolean = false>(options: Options<PutApiApplicationByApplicationIdData, ThrowOnError>) => (options.client ?? client).put<PutApiApplicationByApplicationIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/application/{application_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 查询个人预约
 */
export const getApiUserApplication = <ThrowOnError extends boolean = false>(options: Options<GetApiUserApplicationData, ThrowOnError>) => (options.client ?? client).get<GetApiUserApplicationResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/application',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * 上传文件
 */
export const postApiFile = <ThrowOnError extends boolean = false>(options: Options<PostApiFileData, ThrowOnError>) => (options.client ?? client).post<PostApiFileResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/file',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * 下载文件
 */
export const getApiFileByFiletoken = <ThrowOnError extends boolean = false>(options: Options<GetApiFileByFiletokenData, ThrowOnError>) => (options.client ?? client).get<GetApiFileByFiletokenResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/file/{filetoken}',
    ...options
});

/**
 * 总览所有被管理的账户
 */
export const getApiAccount = <ThrowOnError extends boolean = false>(options?: Options<GetApiAccountData, ThrowOnError>) => (options?.client ?? client).get<GetApiAccountResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/account',
    ...options
});

/**
 * 查看公告
 */
export const getApiNotification = <ThrowOnError extends boolean = false>(options?: Options<GetApiNotificationData, ThrowOnError>) => (options?.client ?? client).get<GetApiNotificationResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/notification',
    ...options
});

/**
 * 发布公告
 */
export const postApiNotification = <ThrowOnError extends boolean = false>(options: Options<PostApiNotificationData, ThrowOnError>) => (options.client ?? client).post<PostApiNotificationResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/notification',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除公告
 */
export const deleteApiNotificationByNotificationId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiNotificationByNotificationIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiNotificationByNotificationIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/notification/{notification_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 更新公告
 */
export const putApiNotificationByNotificationId = <ThrowOnError extends boolean = false>(options: Options<PutApiNotificationByNotificationIdData, ThrowOnError>) => (options.client ?? client).put<PutApiNotificationByNotificationIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/notification/{notification_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 获取管理员发布的系统公告
 */
export const getApiUserNotification = <ThrowOnError extends boolean = false>(options?: Options<GetApiUserNotificationData, ThrowOnError>) => (options?.client ?? client).get<GetApiUserNotificationResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/notification',
    ...options
});

/**
 * 获取用户是否有未读通告
 *
 * 返回用户是否有未读通告，true就是有
 */
export const getApiNotificationRead = <ThrowOnError extends boolean = false>(options?: Options<GetApiNotificationReadData, ThrowOnError>) => (options?.client ?? client).get<GetApiNotificationReadResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/notification/read',
    ...options
});
