// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { DeleteApiAdminAnnouncementData, DeleteApiAdminAnnouncementResponses, DeleteApiReservationByReservationIdData, DeleteApiReservationByReservationIdResponses, GetApiAdminAccountData, GetApiAdminAccountInfoData, GetApiAdminAccountInfoResponses, GetApiAdminAccountResponses, GetApiAdminAnnouncementData, GetApiAdminAnnouncementResponses, GetApiAdminReservationInfoData, GetApiAdminReservationInfoResponses, GetApiAdminRoomData, GetApiAdminRoomReservationsData, GetApiAdminRoomReservationsResponses, GetApiAdminRoomResponses, GetApiGetLoginSessionSaltData, GetApiGetLoginSessionSaltResponses, GetApiUserAnnoucementsData, GetApiUserAnnoucementsResponses, GetApiUserReservationsData, GetApiUserReservationsResponses, GetApiVenueBuildingsData, GetApiVenueBuildingsResponses, GetApiVenueByVenueIdInfoData, GetApiVenueByVenueIdInfoResponses, GetApiVenueCampusesData, GetApiVenueCampusesResponses, GetApiVenueQueryData, GetApiVenueQueryResponses, PatchApiUserEditProfileData, PatchApiUserEditProfileResponses, PostApiAdminAnnoucementData, PostApiAdminAnnoucementResponses, PostApiAdminReservationApprovalData, PostApiAdminReservationApprovalResponses, PostApiLoginData, PostApiLoginResponses, PostApiRegisterData, PostApiRegisterResponses, PostApiUserChangePasswordData, PostApiUserChangePasswordResponses, PostApiVenueByVenueIdReserveData, PostApiVenueByVenueIdReserveResponses, PutApiAdminAnnouncementData, PutApiAdminAnnouncementResponses, PutApiAdminRoomUpdateData, PutApiAdminRoomUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 登录
 */
export const postApiLogin = <ThrowOnError extends boolean = false>(options?: Options<PostApiLoginData, ThrowOnError>) => (options?.client ?? client).post<PostApiLoginResponses, unknown, ThrowOnError>({
    url: '/api/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * 修改密码
 *
 * 修改密码可选验证方式，要求登录验证与表单验证双通过。
 */
export const postApiUserChangePassword = <ThrowOnError extends boolean = false>(options?: Options<PostApiUserChangePasswordData, ThrowOnError>) => (options?.client ?? client).post<PostApiUserChangePasswordResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/change-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * 完善信息
 */
export const patchApiUserEditProfile = <ThrowOnError extends boolean = false>(options?: Options<PatchApiUserEditProfileData, ThrowOnError>) => (options?.client ?? client).patch<PatchApiUserEditProfileResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/edit-profile',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * 用户注册
 */
export const postApiRegister = <ThrowOnError extends boolean = false>(options?: Options<PostApiRegisterData, ThrowOnError>) => (options?.client ?? client).post<PostApiRegisterResponses, unknown, ThrowOnError>({
    url: '/api/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * 获取密码盐值
 */
export const getApiGetLoginSessionSalt = <ThrowOnError extends boolean = false>(options?: Options<GetApiGetLoginSessionSaltData, ThrowOnError>) => (options?.client ?? client).get<GetApiGetLoginSessionSaltResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/get-login-session-salt',
    ...options
});

/**
 * 筛选场地
 *
 * 若没有筛选条件，全都默认为0
 *
 * 场地类别每个场地有且仅有一个，在前端显示为互斥选项；
 * 场地标签每个场地可以具有多个，可拓展；
 * timemap 待讨论；
 */
export const getApiVenueQuery = <ThrowOnError extends boolean = false>(options?: Options<GetApiVenueQueryData, ThrowOnError>) => (options?.client ?? client).get<GetApiVenueQueryResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/venue/query',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options?.headers
    }
});

/**
 * 场地详情
 */
export const getApiVenueByVenueIdInfo = <ThrowOnError extends boolean = false>(options: Options<GetApiVenueByVenueIdInfoData, ThrowOnError>) => (options.client ?? client).get<GetApiVenueByVenueIdInfoResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/venue/{venue_id}/info',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * 预约场地
 *
 * 预约表单需要根据场地详情中的“booking_availability”决定
 * - 如果为“open”，则大部分审批字段可选，下述为此情况下的表单
 * - 如果为“approval”，则大部分审批字段必选
 */
export const postApiVenueByVenueIdReserve = <ThrowOnError extends boolean = false>(options: Options<PostApiVenueByVenueIdReserveData, ThrowOnError>) => (options.client ?? client).post<PostApiVenueByVenueIdReserveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/venue/{venue_id}/reserve',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 取消预约
 */
export const deleteApiReservationByReservationId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiReservationByReservationIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiReservationByReservationIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/reservation/{reservation_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 查询个人预约
 */
export const getApiUserReservations = <ThrowOnError extends boolean = false>(options?: Options<GetApiUserReservationsData, ThrowOnError>) => (options?.client ?? client).get<GetApiUserReservationsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/reservations',
    ...options
});

/**
 * 查询公告/消息
 */
export const getApiUserAnnoucements = <ThrowOnError extends boolean = false>(options?: Options<GetApiUserAnnoucementsData, ThrowOnError>) => (options?.client ?? client).get<GetApiUserAnnoucementsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/annoucements',
    ...options
});

/**
 * 楼列表
 *
 * 获取用户有权读取的楼列表
 */
export const getApiVenueBuildings = <ThrowOnError extends boolean = false>(options?: Options<GetApiVenueBuildingsData, ThrowOnError>) => (options?.client ?? client).get<GetApiVenueBuildingsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/venue/buildings',
    ...options
});

/**
 * 校区列表
 *
 * 获取用户有权读取的校区列表
 */
export const getApiVenueCampuses = <ThrowOnError extends boolean = false>(options?: Options<GetApiVenueCampusesData, ThrowOnError>) => (options?.client ?? client).get<GetApiVenueCampusesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/venue/campuses',
    ...options
});

/**
 * 总览所管场地
 */
export const getApiAdminRoom = <ThrowOnError extends boolean = false>(options?: Options<GetApiAdminRoomData, ThrowOnError>) => (options?.client ?? client).get<GetApiAdminRoomResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/room',
    ...options
});

/**
 * 总览单个场地所有预约
 */
export const getApiAdminRoomReservations = <ThrowOnError extends boolean = false>(options?: Options<GetApiAdminRoomReservationsData, ThrowOnError>) => (options?.client ?? client).get<GetApiAdminRoomReservationsResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/room/reservations',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options?.headers
    }
});

/**
 * 查看预约详情
 */
export const getApiAdminReservationInfo = <ThrowOnError extends boolean = false>(options?: Options<GetApiAdminReservationInfoData, ThrowOnError>) => (options?.client ?? client).get<GetApiAdminReservationInfoResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/reservation/info',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options?.headers
    }
});

/**
 * 审批预约
 */
export const postApiAdminReservationApproval = <ThrowOnError extends boolean = false>(options?: Options<PostApiAdminReservationApprovalData, ThrowOnError>) => (options?.client ?? client).post<PostApiAdminReservationApprovalResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/reservation/approval',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * 更新场地信息
 */
export const putApiAdminRoomUpdate = <ThrowOnError extends boolean = false>(options: Options<PutApiAdminRoomUpdateData, ThrowOnError>) => (options.client ?? client).put<PutApiAdminRoomUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/room/update',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 总览所有被管理的账户
 */
export const getApiAdminAccount = <ThrowOnError extends boolean = false>(options?: Options<GetApiAdminAccountData, ThrowOnError>) => (options?.client ?? client).get<GetApiAdminAccountResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/account',
    ...options
});

/**
 * 查看用户信息
 */
export const getApiAdminAccountInfo = <ThrowOnError extends boolean = false>(options?: Options<GetApiAdminAccountInfoData, ThrowOnError>) => (options?.client ?? client).get<GetApiAdminAccountInfoResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/account/info',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options?.headers
    }
});

/**
 * 发布公告
 */
export const postApiAdminAnnoucement = <ThrowOnError extends boolean = false>(options?: Options<PostApiAdminAnnoucementData, ThrowOnError>) => (options?.client ?? client).post<PostApiAdminAnnoucementResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/annoucement',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * 删除公告
 */
export const deleteApiAdminAnnouncement = <ThrowOnError extends boolean = false>(options?: Options<DeleteApiAdminAnnouncementData, ThrowOnError>) => (options?.client ?? client).delete<DeleteApiAdminAnnouncementResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/announcement',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * 查看发布的公告
 */
export const getApiAdminAnnouncement = <ThrowOnError extends boolean = false>(options?: Options<GetApiAdminAnnouncementData, ThrowOnError>) => (options?.client ?? client).get<GetApiAdminAnnouncementResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/announcement',
    ...options
});

/**
 * 更新公告
 */
export const putApiAdminAnnouncement = <ThrowOnError extends boolean = false>(options?: Options<PutApiAdminAnnouncementData, ThrowOnError>) => (options?.client ?? client).put<PutApiAdminAnnouncementResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/announcement',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});
