// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type PostApiLoginData = {
    body: {
        /**
         * 登录名
         *
         * 可以是用户名、学号或预留联系方式
         */
        login_name: string;
        /**
         * 登录密码哈希结果
         */
        login_token: string;
    };
    path?: never;
    query?: never;
    url: '/api/login';
};

export type PostApiLoginResponses = {
    200: {
        code: number;
        msg: string;
        data: {
            /**
             * 用户唯一编号
             */
            uid: string;
            /**
             * 用户名
             */
            display_name: string;
            /**
             * 登录令牌
             */
            webtoken: string;
        };
    };
};

export type PostApiLoginResponse = PostApiLoginResponses[keyof PostApiLoginResponses];

export type PostApiUserChangePasswordData = {
    body: {
        /**
         * 认证方式
         *
         * 允许旧密码、统一账号密码（用于恢复）等
         */
        verify_type: string;
        /**
         * 认证内容
         *
         * 对应的认证数据
         */
        verify_data: string;
        /**
         * 新密码
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/api/user/change-password';
};

export type PostApiUserChangePasswordResponses = {
    200: {
        code: number;
        msg: string;
        data?: null;
    };
};

export type PostApiUserChangePasswordResponse = PostApiUserChangePasswordResponses[keyof PostApiUserChangePasswordResponses];

export type PatchApiUserEditProfileData = {
    body: {
        phone_number?: string;
    };
    path?: never;
    query?: never;
    url: '/api/user/edit-profile';
};

export type PatchApiUserEditProfileResponses = {
    200: {
        code: number;
        msg: string;
        data: null;
    };
};

export type PatchApiUserEditProfileResponse = PatchApiUserEditProfileResponses[keyof PatchApiUserEditProfileResponses];

export type PostApiRegisterData = {
    body: {
        username: string;
        school_id: string;
        /**
         * 1234
         */
        password_hash: string;
        password_salt: string;
    };
    path?: never;
    query?: never;
    url: '/api/register';
};

export type PostApiRegisterResponses = {
    200: {
        code: number;
        msg: string;
        data: string | number | boolean | Array<unknown> | {
            [key: string]: unknown;
        } | number | null;
    };
};

export type PostApiRegisterResponse = PostApiRegisterResponses[keyof PostApiRegisterResponses];

export type GetApiLoginSessionSaltData = {
    body?: never;
    path?: never;
    query?: {
        login_name?: string;
    };
    url: '/api/login-session-salt';
};

export type GetApiLoginSessionSaltResponses = {
    200: {
        code: number;
        msg: string;
        data: {
            user_salt: string;
            session_salt: string;
        };
    };
};

export type GetApiLoginSessionSaltResponse = GetApiLoginSessionSaltResponses[keyof GetApiLoginSessionSaltResponses];

export type GetApiVenueQueryData = {
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        /**
         * 场地类别
         */
        type?: string;
        /**
         * 场地标签
         */
        tags?: Array<string>;
        capacity?: Array<string>;
        campus?: string;
        building?: string;
    };
    url: '/api/venue/query';
};

export type GetApiVenueQueryResponses = {
    200: {
        code: number;
        msg: string;
        data: Array<{
            venue_name: string;
            venue_type: string;
            venue_tags: string;
            capacity: number;
            min_request?: number;
            timemap: {
                [key: string]: unknown;
            };
            cover_image_url: string;
            availability: string;
        }>;
    };
};

export type GetApiVenueQueryResponse = GetApiVenueQueryResponses[keyof GetApiVenueQueryResponses];

export type GetApiVenueByVenueIdInfoData = {
    body: {
        [key: string]: unknown;
    };
    path: {
        venue_id: string;
    };
    query?: never;
    url: '/api/venue/{venue_id}/info';
};

export type GetApiVenueByVenueIdInfoResponses = {
    200: {
        code: number;
        msg: string;
        data: {
            image_url: Array<string>;
            venue_type: string;
            venue_name: string;
            capacity: number;
            timemap: {
                [key: string]: unknown;
            };
            available_equipments?: Array<string>;
            availability: string;
        };
    };
};

export type GetApiVenueByVenueIdInfoResponse = GetApiVenueByVenueIdInfoResponses[keyof GetApiVenueByVenueIdInfoResponses];

export type PostApiVenueByVenueIdReserveData = {
    body: {
        time_request: {
            [key: string]: unknown;
        };
        /**
         * 预估人数
         */
        estimated_participants: number;
        activity_name?: string;
        /**
         * 举办方，组织或个人名称
         */
        organizer?: string;
        contacts?: Array<{
            name: string;
            phone_number: string;
            /**
             * 若该用户未注册，此项可空
             */
            user_id?: string;
            email?: string;
        }>;
        /**
         * 活动简要说明
         */
        description?: string;
        /**
         * 附件
         */
        attachments_url?: Array<string>;
    };
    path: {
        venue_id: string;
    };
    query?: never;
    url: '/api/venue/{venue_id}/reserve';
};

export type PostApiVenueByVenueIdReserveResponses = {
    200: {
        code: number;
        msg: string;
        data: {
            reservation_id: number;
        };
    };
};

export type PostApiVenueByVenueIdReserveResponse = PostApiVenueByVenueIdReserveResponses[keyof PostApiVenueByVenueIdReserveResponses];

export type DeleteApiReservationByReservationIdData = {
    body: {
        [key: string]: unknown;
    };
    path: {
        reservation_id: string;
    };
    query?: never;
    url: '/api/reservation/{reservation_id}';
};

export type DeleteApiReservationByReservationIdResponses = {
    200: {
        code: number;
        msg: string;
        data?: null;
    };
};

export type DeleteApiReservationByReservationIdResponse = DeleteApiReservationByReservationIdResponses[keyof DeleteApiReservationByReservationIdResponses];

export type GetApiUserReservationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/reservations';
};

export type GetApiUserReservationsResponses = {
    200: {
        code: number;
        msg: string;
        data: Array<{
            reservation_id: number;
            venue_name: string;
            reservation_time: {
                [key: string]: unknown;
            };
            activity_name?: string;
            status: string;
        }>;
    };
};

export type GetApiUserReservationsResponse = GetApiUserReservationsResponses[keyof GetApiUserReservationsResponses];

export type GetApiUserAnnoucementsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/annoucements';
};

export type GetApiUserAnnoucementsResponses = {
    200: {
        code: number;
        msg: string;
        data: Array<{
            announcer: string;
            title: string;
            content: string;
        }>;
    };
};

export type GetApiUserAnnoucementsResponse = GetApiUserAnnoucementsResponses[keyof GetApiUserAnnoucementsResponses];

export type GetApiVenueBuildingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/venue/buildings';
};

export type GetApiVenueBuildingsResponses = {
    200: Array<{
        name: string;
        campus_id: number;
        building_id: number;
    }>;
};

export type GetApiVenueBuildingsResponse = GetApiVenueBuildingsResponses[keyof GetApiVenueBuildingsResponses];

export type GetApiVenueCampusesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/venue/campuses';
};

export type GetApiVenueCampusesResponses = {
    200: Array<{
        name: string;
        campus_id: number;
    }>;
};

export type GetApiVenueCampusesResponse = GetApiVenueCampusesResponses[keyof GetApiVenueCampusesResponses];

export type GetApiAdminRoomData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/room';
};

export type GetApiAdminRoomResponses = {
    200: {
        code: number;
        msg: string;
        data: Array<{
            reservations_sum: number;
            refusion_sum: number;
            acceptance_sum: number;
            room: string;
        }>;
    };
};

export type GetApiAdminRoomResponse = GetApiAdminRoomResponses[keyof GetApiAdminRoomResponses];

export type GetApiAdminRoomReservationsData = {
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        room?: string;
    };
    url: '/api/admin/room/reservations';
};

export type GetApiAdminRoomReservationsResponses = {
    200: {
        code: number;
        msg: string;
        data: Array<{
            reserve_id: number;
            activity_name: string;
            time: string;
        }>;
    };
};

export type GetApiAdminRoomReservationsResponse = GetApiAdminRoomReservationsResponses[keyof GetApiAdminRoomReservationsResponses];

export type GetApiAdminReservationInfoData = {
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        reserve_id?: number;
    };
    url: '/api/admin/reservation/info';
};

export type GetApiAdminReservationInfoResponses = {
    200: {
        code: number;
        msg: string;
        data: {
            activity_name: string;
            time: string;
            organizer: string;
            phone_number: string;
            contact_person: string;
            people_num: number;
            remarks: string;
            event_plan_file: string;
        };
    };
};

export type GetApiAdminReservationInfoResponse = GetApiAdminReservationInfoResponses[keyof GetApiAdminReservationInfoResponses];

export type PostApiAdminReservationApprovalData = {
    body: {
        reserve_id: number;
        /**
         * 1同意2驳回
         */
        approval: number;
    };
    path?: never;
    query?: never;
    url: '/api/admin/reservation/approval';
};

export type PostApiAdminReservationApprovalResponses = {
    200: {
        code: number;
        msg: string;
        data: null;
    };
};

export type PostApiAdminReservationApprovalResponse = PostApiAdminReservationApprovalResponses[keyof PostApiAdminReservationApprovalResponses];

export type PutApiVenueByVenueIdData = {
    body: {
        pictures: Array<string>;
        capacity: number;
        availability: boolean;
        room: string;
    };
    path: {
        venue_id: string;
    };
    query?: never;
    url: '/api/venue/{venue_id}';
};

export type PutApiVenueByVenueIdResponses = {
    200: {
        code: number;
        msg: string;
        data: null;
    };
};

export type PutApiVenueByVenueIdResponse = PutApiVenueByVenueIdResponses[keyof PutApiVenueByVenueIdResponses];

export type GetApiAdminAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/account';
};

export type GetApiAdminAccountResponses = {
    200: {
        code: number;
        msg: string;
        data: Array<{
            name: string;
            character: number;
            stu_id: string;
        }>;
    };
};

export type GetApiAdminAccountResponse = GetApiAdminAccountResponses[keyof GetApiAdminAccountResponses];

export type GetApiAdminAccountInfoData = {
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        stu_id?: string;
    };
    url: '/api/admin/account/info';
};

export type GetApiAdminAccountInfoResponses = {
    200: {
        code: number;
        msg: string;
        data: {
            reservation_sum: number;
            cancel_sum: number;
            use_sum: number;
        };
    };
};

export type GetApiAdminAccountInfoResponse = GetApiAdminAccountInfoResponses[keyof GetApiAdminAccountInfoResponses];

export type PostApiAdminAnnoucementData = {
    body: {
        /**
         * 全站公告默认为null
         */
        recevier: string;
        title: string;
        content: string;
        pictures: Array<string>;
        /**
         * 1发布2定时发布3草稿
         */
        status: number;
        release_time: string;
    };
    path?: never;
    query?: never;
    url: '/api/admin/annoucement';
};

export type PostApiAdminAnnoucementResponses = {
    200: {
        code: number;
        msg: string;
        data: null;
    };
};

export type PostApiAdminAnnoucementResponse = PostApiAdminAnnoucementResponses[keyof PostApiAdminAnnoucementResponses];

export type DeleteApiAdminAnnouncementData = {
    body: {
        announcement_id: number;
    };
    path?: never;
    query?: never;
    url: '/api/admin/announcement';
};

export type DeleteApiAdminAnnouncementResponses = {
    200: {
        code: number;
        msg: string;
        data: null;
    };
};

export type DeleteApiAdminAnnouncementResponse = DeleteApiAdminAnnouncementResponses[keyof DeleteApiAdminAnnouncementResponses];

export type GetApiAdminAnnouncementData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/announcement';
};

export type GetApiAdminAnnouncementResponses = {
    200: {
        code: number;
        msg: string;
        data: Array<{
            annoucement_id: number;
            title: string;
            release_time: string;
            status: string;
        }>;
    };
};

export type GetApiAdminAnnouncementResponse = GetApiAdminAnnouncementResponses[keyof GetApiAdminAnnouncementResponses];

export type PutApiAdminAnnouncementData = {
    body: {
        announcement_id: number;
        recevier: string;
        title: string;
        content: string;
        pictures: Array<string>;
        status: number;
        release_time: string;
    };
    path?: never;
    query?: never;
    url: '/api/admin/announcement';
};

export type PutApiAdminAnnouncementResponses = {
    200: {
        code: number;
        msg: string;
        data: null;
    };
};

export type PutApiAdminAnnouncementResponse = PutApiAdminAnnouncementResponses[keyof PutApiAdminAnnouncementResponses];
