// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type PostApiLoginData = {
    body: {
        /**
         * 登录名
         *
         * 可以是用户名、学号或预留联系方式
         */
        login_name: string;
        /**
         * 登录密码哈希结果
         */
        login_token: string;
    };
    path?: never;
    query?: never;
    url: '/api/login';
};

export type PostApiLoginResponses = {
    200: {
        code: number;
        msg: string;
        data: {
            /**
             * 用户名
             */
            display_name: string;
            /**
             * 用户唯一编号
             */
            uid: string;
            /**
             * 登录令牌
             */
            webtoken: string;
        };
    };
};

export type PostApiLoginResponse = PostApiLoginResponses[keyof PostApiLoginResponses];

export type PostApiUserChangePasswordData = {
    body: {
        /**
         * 认证方式
         *
         * 允许旧密码、统一账号密码（用于恢复）等
         */
        verify_type: string;
        /**
         * 认证内容
         *
         * 对应的认证数据
         */
        verify_data: string;
        /**
         * 新密码
         */
        new_password: string;
        new_salt: string;
    };
    path?: never;
    query?: never;
    url: '/api/user/change-password';
};

export type PostApiUserChangePasswordResponses = {
    200: {
        code: number;
        msg: string;
        data?: null;
    };
};

export type PostApiUserChangePasswordResponse = PostApiUserChangePasswordResponses[keyof PostApiUserChangePasswordResponses];

export type PutApiUserProfileData = {
    body: {
        phone_number?: string;
        username: string;
    };
    path?: never;
    query?: never;
    url: '/api/user/profile';
};

export type PutApiUserProfileResponses = {
    200: {
        code: number;
        msg: string;
        data: null;
    };
};

export type PutApiUserProfileResponse = PutApiUserProfileResponses[keyof PutApiUserProfileResponses];

export type PostApiRegisterData = {
    body: {
        username: string;
        school_id: string;
        /**
         * 1234
         */
        password_hash: string;
        password_salt: string;
    };
    path?: never;
    query?: never;
    url: '/api/register';
};

export type PostApiRegisterResponses = {
    200: {
        code: number;
        msg: string;
        data: string | number | boolean | Array<unknown> | {
            [key: string]: unknown;
        } | number | null;
    };
};

export type PostApiRegisterResponse = PostApiRegisterResponses[keyof PostApiRegisterResponses];

export type GetApiLoginSessionSaltData = {
    body?: never;
    path?: never;
    query?: {
        login_name?: string;
    };
    url: '/api/login-session-salt';
};

export type GetApiLoginSessionSaltResponses = {
    200: {
        code: number;
        msg: string;
        data: {
            user_salt: string;
            session_salt: string;
        };
    };
};

export type GetApiLoginSessionSaltResponse = GetApiLoginSessionSaltResponses[keyof GetApiLoginSessionSaltResponses];

export type GetApiVenueData = {
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        /**
         * 筛选位于特定楼区（building_id）的场地
         */
        b?: Array<string>;
        /**
         * 筛选具有特定标签（type_id）的场地
         */
        t?: Array<string>;
        /**
         * 筛选用户具有特定权限的场地，值可以为R/A/M/E的任意组合，对应四种场地权限
         */
        p?: string;
        /**
         * 搜索关键词
         */
        s?: string;
        /**
         * 分页偏移（offset）
         */
        o?: string;
        /**
         * 单页最大（pagesize），无此项默认 12
         */
        n?: string;
    };
    url: '/api/venue';
};

export type GetApiVenueResponses = {
    200: {
        code: number;
        msg: string;
        data: Array<{
            venue_id: number;
            name: string;
            building_id: number;
            type_id: number;
            capacity?: number;
            description_text: string;
            cover_image_token: string;
            permissions: Array<string>;
            attachments: Array<{
                type: string;
                index: number;
                file_token: string;
            }>;
            timetable: Array<{
                start: string;
                end: string;
            }>;
        }>;
    };
};

export type GetApiVenueResponse = GetApiVenueResponses[keyof GetApiVenueResponses];

export type PutApiVenueData = {
    body: {
        name: string;
        building_id: number;
        type_id: number;
        description: string;
        cover_image_token: string;
        images_token: Array<string>;
        capacity: number;
        /**
         * 预留字段
         */
        equipment?: string;
    };
    path?: never;
    query?: never;
    url: '/api/venue';
};

export type PutApiVenueResponses = {
    200: {
        code: number;
        msg: string;
        data: {
            venue_id: number;
        };
    };
};

export type PutApiVenueResponse = PutApiVenueResponses[keyof PutApiVenueResponses];

export type DeleteApiVenueByVenueIdData = {
    body?: never;
    path: {
        venue_id: string;
    };
    query?: never;
    url: '/api/venue/{venue_id}';
};

export type DeleteApiVenueByVenueIdResponses = {
    200: {
        code: number;
        msg: string;
        data: string | number | boolean | Array<unknown> | {
            [key: string]: unknown;
        } | number | null;
    };
};

export type DeleteApiVenueByVenueIdResponse = DeleteApiVenueByVenueIdResponses[keyof DeleteApiVenueByVenueIdResponses];

export type PutApiVenueByVenueIdData = {
    body: {
        name: string;
        capacity: number;
        building_id: number;
        type_id: number;
        description: string;
        cover_image_token: string;
        images_token: Array<string>;
    };
    path: {
        venue_id: string;
    };
    query?: never;
    url: '/api/venue/{venue_id}';
};

export type PutApiVenueByVenueIdResponses = {
    200: {
        code: number;
        msg: string;
        data: string | number | boolean | Array<unknown> | {
            [key: string]: unknown;
        } | number | null;
    };
};

export type PutApiVenueByVenueIdResponse = PutApiVenueByVenueIdResponses[keyof PutApiVenueByVenueIdResponses];

export type GetApiVenueLocationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/venue/locations';
};

export type GetApiVenueLocationsResponses = {
    200: {
        code: number;
        msg: string;
        data: {
            buildings: Array<{
                building_id: number;
                building_name: string;
                location_campus_id: number;
            }>;
            campuses: Array<{
                campus_id: number;
                campus_name: string;
            }>;
        };
    };
};

export type GetApiVenueLocationsResponse = GetApiVenueLocationsResponses[keyof GetApiVenueLocationsResponses];

export type GetApiVenueByVenueIdApplicationData = {
    body: {
        [key: string]: unknown;
    };
    path: {
        venue_id: string;
    };
    query?: never;
    url: '/api/venue/{venue_id}/application';
};

export type GetApiVenueByVenueIdApplicationResponses = {
    200: {
        code: number;
        msg: string;
        data: Array<Array<{
            id: number;
            application_type: string;
            application_status: string;
            time_request: Array<{
                begin: string;
                end: string;
            }>;
            estimated_participants: number;
            description: string;
            attachments: Array<{
                index: number;
                file_token: string;
                file_type: string;
                file_name: string;
            }>;
            activity_name: string;
            activity_organizer: string;
            activity_coordinator: string | number | boolean | Array<unknown> | {
                [key: string]: unknown;
            } | number | null;
            comments: Array<{
                id: number;
                text: string;
                attachments: Array<{
                    index: number;
                    file_token: string;
                    file_type: string;
                    file_name: string;
                }>;
            }>;
        }>>;
    };
};

export type GetApiVenueByVenueIdApplicationResponse = GetApiVenueByVenueIdApplicationResponses[keyof GetApiVenueByVenueIdApplicationResponses];

export type PostApiVenueByVenueIdApplicationData = {
    body: {
        time_request: Array<{
            begin: string;
            end: string;
        }>;
        /**
         * 预估人数
         */
        estimated_participants: number;
        activity_name: string;
        /**
         * 举办方，组织或个人名称
         */
        activity_organizer: string;
        /**
         * 活动简要说明
         */
        description: string;
        /**
         * 附件
         */
        attachments: Array<{
            index: number;
            file_token: string;
            file_name: string;
            file_type: string;
        }>;
        activity_coordinator: Array<string | number | boolean | Array<unknown> | {
            [key: string]: unknown;
        } | number | null>;
        application_type: string;
    };
    path: {
        venue_id: string;
    };
    query?: never;
    url: '/api/venue/{venue_id}/application';
};

export type PostApiVenueByVenueIdApplicationResponses = {
    200: {
        code: number;
        msg: string;
        data?: string | number | boolean | Array<unknown> | {
            [key: string]: unknown;
        } | number | null;
    };
};

export type PostApiVenueByVenueIdApplicationResponse = PostApiVenueByVenueIdApplicationResponses[keyof PostApiVenueByVenueIdApplicationResponses];

export type DeleteApiApplicationByApplicationIdData = {
    body: {
        [key: string]: unknown;
    };
    path: {
        application_id: string;
    };
    query?: never;
    url: '/api/application/{application_id}';
};

export type DeleteApiApplicationByApplicationIdResponses = {
    200: {
        code: number;
        msg: string;
        data?: null;
    };
};

export type DeleteApiApplicationByApplicationIdResponse = DeleteApiApplicationByApplicationIdResponses[keyof DeleteApiApplicationByApplicationIdResponses];

export type PutApiApplicationByApplicationIdData = {
    body: {
        decision: string;
        comment: {
            id: number;
            text: string;
            attachments: Array<{
                index: number;
                file_token: string;
                file_type: string;
                file_name: string;
            }>;
        };
        known_conflicts: Array<number>;
    };
    path: {
        application_id: string;
    };
    query?: never;
    url: '/api/application/{application_id}';
};

export type PutApiApplicationByApplicationIdResponses = {
    200: {
        code: number;
        msg: string;
        data: string | number | boolean | Array<unknown> | {
            [key: string]: unknown;
        } | number | null;
    };
};

export type PutApiApplicationByApplicationIdResponse = PutApiApplicationByApplicationIdResponses[keyof PutApiApplicationByApplicationIdResponses];

export type GetApiUserApplicationData = {
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/user/application';
};

export type GetApiUserApplicationResponses = {
    200: {
        code: number;
        msg: string;
        data: Array<Array<{
            id: number;
            application_type: string;
            application_status: string;
            time_request: Array<{
                begin: string;
                end: string;
            }>;
            estimated_participants: number;
            description: string;
            attachments: Array<{
                index: number;
                file_token: string;
                file_type: string;
                file_name: string;
            }>;
            activity_name: string;
            activity_organizer: string;
            activity_coordinator: string | number | boolean | Array<unknown> | {
                [key: string]: unknown;
            } | number | null;
            comments: Array<{
                id: number;
                text: string;
                attachments: Array<{
                    index: number;
                    file_token: string;
                    file_type: string;
                    file_name: string;
                }>;
            }>;
        }>>;
    };
};

export type GetApiUserApplicationResponse = GetApiUserApplicationResponses[keyof GetApiUserApplicationResponses];

export type PostApiFileData = {
    body: {
        size?: number;
        hash?: string;
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/file';
};

export type PostApiFileResponses = {
    200: {
        code: number;
        msg: string;
        data: string | number | boolean | Array<unknown> | {
            [key: string]: unknown;
        } | number | null;
    };
};

export type PostApiFileResponse = PostApiFileResponses[keyof PostApiFileResponses];

export type GetApiFileByFiletokenData = {
    body?: never;
    path: {
        filetoken: string;
    };
    query?: never;
    url: '/api/file/{filetoken}';
};

export type GetApiFileByFiletokenResponses = {
    200: {
        code: number;
        msg: string;
        data: string | number | boolean | Array<unknown> | {
            [key: string]: unknown;
        } | number | null;
    };
};

export type GetApiFileByFiletokenResponse = GetApiFileByFiletokenResponses[keyof GetApiFileByFiletokenResponses];

export type GetApiAccountData = {
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        /**
         * 默认0，学生1，教师2
         */
        identity?: number;
        avg_id?: number;
        offset?: string;
        limit?: string;
    };
    url: '/api/account';
};

export type GetApiAccountResponses = {
    200: {
        code: number;
        msg: string;
        data: Array<{
            name: string;
            identity: number;
            avg_id: number;
            applications_num: {
                total_applications: number;
                cancel: number;
                use: number;
                /**
                 * 如果没有审核权限，则这个字段为-1
                 */
                review: number;
            };
        }>;
    };
};

export type GetApiAccountResponse = GetApiAccountResponses[keyof GetApiAccountResponses];

export type GetApiNotificationData = {
    body?: never;
    path?: never;
    query?: {
        offset?: string;
        limit?: string;
    };
    url: '/api/notification';
};

export type GetApiNotificationResponses = {
    200: {
        code: number;
        msg: string;
        data: Array<{
            notification_id: number;
            title: string;
            release_time: string;
            status: number;
            content: string;
            images_token: Array<string>;
        }>;
    };
};

export type GetApiNotificationResponse = GetApiNotificationResponses[keyof GetApiNotificationResponses];

export type PostApiNotificationData = {
    body: {
        /**
         * 全站公告默认为null
         */
        recevier_uid: string;
        title: string;
        content: string;
        images_token: Array<string>;
        video_token: string;
        /**
         * 1发布2定时发布3草稿
         */
        status: number;
        release_time: string;
    };
    path?: never;
    query?: never;
    url: '/api/notification';
};

export type PostApiNotificationResponses = {
    200: {
        code: number;
        msg: string;
        data: {
            notification_id: number;
        };
    };
};

export type PostApiNotificationResponse = PostApiNotificationResponses[keyof PostApiNotificationResponses];

export type DeleteApiNotificationByNotificationIdData = {
    body: {
        [key: string]: unknown;
    };
    path: {
        notification_id: string;
    };
    query?: never;
    url: '/api/notification/{notification_id}';
};

export type DeleteApiNotificationByNotificationIdResponses = {
    200: {
        code: number;
        msg: string;
        data: null;
    };
};

export type DeleteApiNotificationByNotificationIdResponse = DeleteApiNotificationByNotificationIdResponses[keyof DeleteApiNotificationByNotificationIdResponses];

export type PutApiNotificationByNotificationIdData = {
    body: {
        recevier: string;
        title: string;
        content: string;
        images_token: Array<string>;
        status: number;
        release_time: string;
    };
    path: {
        notification_id: string;
    };
    query?: never;
    url: '/api/notification/{notification_id}';
};

export type PutApiNotificationByNotificationIdResponses = {
    200: {
        code: number;
        msg: string;
        data: null;
    };
};

export type PutApiNotificationByNotificationIdResponse = PutApiNotificationByNotificationIdResponses[keyof PutApiNotificationByNotificationIdResponses];
