// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

export const vPostApiLoginData = v.object({
    body: v.object({
        login_name: v.string(),
        login_token: v.string()
    }),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vPostApiUserChangePasswordData = v.object({
    body: v.object({
        verify_type: v.string(),
        verify_data: v.string(),
        new_password: v.string(),
        new_salt: v.string()
    }),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vPutApiUserProfileData = v.object({
    body: v.object({
        phone_number: v.optional(v.string()),
        username: v.string()
    }),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vPostApiRegisterData = v.object({
    body: v.object({
        username: v.string(),
        school_id: v.string(),
        password_hash: v.string(),
        password_salt: v.string()
    }),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vGetApiLoginSessionSaltData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.object({
        login_name: v.optional(v.string())
    }))
});

export const vGetApiVenueData = v.object({
    body: v.record(v.string(), v.unknown()),
    path: v.optional(v.never()),
    query: v.optional(v.object({
        b: v.optional(v.array(v.string())),
        t: v.optional(v.array(v.string())),
        p: v.optional(v.string()),
        s: v.optional(v.string()),
        o: v.optional(v.string()),
        n: v.optional(v.string())
    }))
});

export const vPutApiVenueData = v.object({
    body: v.object({
        name: v.string(),
        building_id: v.pipe(v.number(), v.integer()),
        type_id: v.pipe(v.number(), v.integer()),
        description: v.string(),
        cover_image_token: v.string(),
        images_token: v.array(v.string()),
        capacity: v.pipe(v.number(), v.integer()),
        equipment: v.optional(v.string())
    }),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vDeleteApiVenueByVenueIdData = v.object({
    body: v.optional(v.never()),
    path: v.object({
        venue_id: v.string()
    }),
    query: v.optional(v.never())
});

export const vPutApiVenueByVenueIdData = v.object({
    body: v.object({
        name: v.string(),
        capacity: v.pipe(v.number(), v.integer()),
        building_id: v.pipe(v.number(), v.integer()),
        type_id: v.pipe(v.number(), v.integer()),
        description: v.string(),
        cover_image_token: v.string(),
        images_token: v.array(v.string())
    }),
    path: v.object({
        venue_id: v.string()
    }),
    query: v.optional(v.never())
});

export const vGetApiVenueLocationsData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vGetApiVenueByVenueIdApplicationData = v.object({
    body: v.record(v.string(), v.unknown()),
    path: v.object({
        venue_id: v.string()
    }),
    query: v.optional(v.never())
});

export const vPostApiVenueByVenueIdApplicationData = v.object({
    body: v.object({
        time_request: v.array(v.object({
            begin: v.string(),
            end: v.string()
        })),
        estimated_participants: v.pipe(v.number(), v.integer()),
        activity_name: v.string(),
        activity_organizer: v.string(),
        description: v.string(),
        attachments: v.array(v.object({
            index: v.pipe(v.number(), v.integer()),
            file_token: v.string(),
            file_name: v.string(),
            file_type: v.string()
        })),
        activity_coordinator: v.array(v.union([
            v.string(),
            v.pipe(v.number(), v.integer()),
            v.boolean(),
            v.array(v.unknown()),
            v.record(v.string(), v.unknown()),
            v.number(),
            v.null()
        ])),
        application_type: v.string()
    }),
    path: v.object({
        venue_id: v.string()
    }),
    query: v.optional(v.never())
});

export const vDeleteApiApplicationByApplicationIdData = v.object({
    body: v.record(v.string(), v.unknown()),
    path: v.object({
        application_id: v.string()
    }),
    query: v.optional(v.never())
});

export const vPutApiApplicationByApplicationIdData = v.object({
    body: v.object({
        decision: v.string(),
        comment: v.object({
            id: v.pipe(v.number(), v.integer()),
            text: v.string(),
            attachments: v.array(v.object({
                index: v.pipe(v.number(), v.integer()),
                file_token: v.string(),
                file_type: v.string(),
                file_name: v.string()
            }))
        }),
        known_conflicts: v.array(v.pipe(v.number(), v.integer()))
    }),
    path: v.object({
        application_id: v.string()
    }),
    query: v.optional(v.never())
});

export const vGetApiUserApplicationData = v.object({
    body: v.record(v.string(), v.unknown()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vPostApiFileData = v.object({
    body: v.object({
        size: v.optional(v.pipe(v.number(), v.integer())),
        hash: v.optional(v.string()),
        file: v.optional(v.string())
    }),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vGetApiFileByFiletokenData = v.object({
    body: v.optional(v.never()),
    path: v.object({
        filetoken: v.string()
    }),
    query: v.optional(v.never())
});

export const vGetApiAccountData = v.object({
    body: v.record(v.string(), v.unknown()),
    path: v.optional(v.never()),
    query: v.optional(v.object({
        identity: v.optional(v.pipe(v.number(), v.integer())),
        avg_id: v.optional(v.pipe(v.number(), v.integer())),
        offset: v.optional(v.string()),
        limit: v.optional(v.string())
    }))
});

export const vGetApiNotificationData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.object({
        offset: v.optional(v.string()),
        limit: v.optional(v.string())
    }))
});

export const vPostApiNotificationData = v.object({
    body: v.object({
        recevier_uid: v.string(),
        title: v.string(),
        content: v.string(),
        images_token: v.array(v.string()),
        video_token: v.string(),
        status: v.pipe(v.number(), v.integer()),
        release_time: v.string()
    }),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vDeleteApiNotificationByNotificationIdData = v.object({
    body: v.record(v.string(), v.unknown()),
    path: v.object({
        notification_id: v.string()
    }),
    query: v.optional(v.never())
});

export const vPutApiNotificationByNotificationIdData = v.object({
    body: v.object({
        recevier: v.string(),
        title: v.string(),
        content: v.string(),
        images_token: v.array(v.string()),
        status: v.pipe(v.number(), v.integer()),
        release_time: v.string()
    }),
    path: v.object({
        notification_id: v.string()
    }),
    query: v.optional(v.never())
});
