// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

export const vPostApiLoginData = v.object({
    body: v.object({
        login_name: v.string(),
        login_token: v.string()
    }),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vPostApiUserChangePasswordData = v.object({
    body: v.object({
        verify_type: v.string(),
        verify_data: v.string(),
        new_password: v.string()
    }),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vPatchApiUserEditProfileData = v.object({
    body: v.object({
        phone_number: v.optional(v.string())
    }),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vPostApiRegisterData = v.object({
    body: v.object({
        username: v.string(),
        school_id: v.string(),
        password_hash: v.string(),
        password_salt: v.string()
    }),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vGetApiLoginSessionSaltData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.object({
        login_name: v.optional(v.string())
    }))
});

export const vGetApiVenueQueryData = v.object({
    body: v.record(v.string(), v.unknown()),
    path: v.optional(v.never()),
    query: v.optional(v.object({
        type: v.optional(v.string()),
        tags: v.optional(v.array(v.string())),
        capacity: v.optional(v.array(v.string())),
        campus: v.optional(v.string()),
        building: v.optional(v.string())
    }))
});

export const vGetApiVenueByVenueIdInfoData = v.object({
    body: v.record(v.string(), v.unknown()),
    path: v.object({
        venue_id: v.string()
    }),
    query: v.optional(v.never())
});

export const vPostApiVenueByVenueIdReserveData = v.object({
    body: v.object({
        time_request: v.record(v.string(), v.unknown()),
        estimated_participants: v.pipe(v.number(), v.integer()),
        activity_name: v.optional(v.string()),
        organizer: v.optional(v.string()),
        contacts: v.optional(v.array(v.object({
            name: v.string(),
            phone_number: v.string(),
            user_id: v.optional(v.string()),
            email: v.optional(v.string())
        }))),
        description: v.optional(v.string()),
        attachments_url: v.optional(v.array(v.string()))
    }),
    path: v.object({
        venue_id: v.string()
    }),
    query: v.optional(v.never())
});

export const vDeleteApiReservationByReservationIdData = v.object({
    body: v.record(v.string(), v.unknown()),
    path: v.object({
        reservation_id: v.string()
    }),
    query: v.optional(v.never())
});

export const vGetApiUserReservationsData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vGetApiUserAnnoucementsData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vGetApiVenueBuildingsData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vGetApiVenueCampusesData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vGetApiAdminRoomData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vGetApiAdminRoomReservationsData = v.object({
    body: v.record(v.string(), v.unknown()),
    path: v.optional(v.never()),
    query: v.optional(v.object({
        room: v.optional(v.string())
    }))
});

export const vGetApiAdminReservationInfoData = v.object({
    body: v.record(v.string(), v.unknown()),
    path: v.optional(v.never()),
    query: v.optional(v.object({
        reserve_id: v.optional(v.pipe(v.number(), v.integer()))
    }))
});

export const vPostApiAdminReservationApprovalData = v.object({
    body: v.object({
        reserve_id: v.pipe(v.number(), v.integer()),
        approval: v.pipe(v.number(), v.integer())
    }),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vPutApiVenueByVenueIdData = v.object({
    body: v.object({
        pictures: v.array(v.string()),
        capacity: v.pipe(v.number(), v.integer()),
        availability: v.boolean(),
        room: v.string()
    }),
    path: v.object({
        venue_id: v.string()
    }),
    query: v.optional(v.never())
});

export const vGetApiAdminAccountData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vGetApiAdminAccountInfoData = v.object({
    body: v.record(v.string(), v.unknown()),
    path: v.optional(v.never()),
    query: v.optional(v.object({
        stu_id: v.optional(v.string())
    }))
});

export const vPostApiAdminAnnoucementData = v.object({
    body: v.object({
        recevier: v.string(),
        title: v.string(),
        content: v.string(),
        pictures: v.array(v.string()),
        status: v.pipe(v.number(), v.integer()),
        release_time: v.string()
    }),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vDeleteApiAdminAnnouncementData = v.object({
    body: v.object({
        announcement_id: v.pipe(v.number(), v.integer())
    }),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vGetApiAdminAnnouncementData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

export const vPutApiAdminAnnouncementData = v.object({
    body: v.object({
        announcement_id: v.pipe(v.number(), v.integer()),
        recevier: v.string(),
        title: v.string(),
        content: v.string(),
        pictures: v.array(v.string()),
        status: v.pipe(v.number(), v.integer()),
        release_time: v.string()
    }),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});
